### ISSUE TITLE
The Kingsmouth Code

### ISSUE THREAD

**Issue by Darxide23** [Judgy53/SWL-ComputerPuzzleHelper#1]
Could you please put The Kingsmouth Code into the addon, please? It's part of my daily challenge milk run and I know a lot of other people run it as well since it's so fast.

Thanks!

Edit: I wonder how easy it would be to restructure the addon so that missions can be added by the user instead of being hardcoded?

**Comment by Judgy53** [comment]
Here you go : https://github.com/Judgy53/SWL-ComputerPuzzleHelper/releases/tag/1.5
Fun fact, inputting "password" on the computer of that mission shows you a special text.

I've thinking about allowing the creation of new missions and I have a vague idea of how I would do it. I'll probably give it a try in the next few days/weeks, I'll keep you updated when I have something working :)

EDIT: ~~While doing my KD route, I noticed that it sometimes stop to work completely. Reloading the UI "fixes" it for a while (which makes it hard for me to debug)~~ FIXED ! I messed up while fixing another bug, v1.5 should work fine.
