### ISSUE TITLE
The Broadcast

### ISSUE THREAD

**Issue by theckhd** [Judgy53/SWL-ComputerPuzzleHelper#2]
I know you're not active anymore, but if it's not too difficult to add new missions, would you consider adding The Broadcast?

http://legacy.tswdb.com/missions/seasonal/the-broadcast

Probably just tier 3 is needed.

**Comment by Judgy53** [comment]
https://github.com/Judgy53/SWL-ComputerPuzzleHelper/releases/tag/1.6
The auto close at the end of tier 3 doesn't work, but debugging that could take a week (only 1 attempt per mission completion) so I won't even try ^^
